### Health Check

GET http://{{ezstream_host}}:{{ezstream_port}}/health_check


### Next

GET http://{{ezstream_host}}:{{ezstream_port}}/{{mount_tech}}/next

###


GET http://{{ezstream_host}}:{{ezstream_port}}/{{mount_ambient}}/next