### Health Check

GET http://{{host}}:{{port}}/health_check

### Update database from meta.json

GET http://{{host}}:{{port}}/internal/update_db

### Start ezstream

GET http://{{host}}:{{port}}/internal/{{mount}}/update

###################### EZSTREAM API


### Health Check

GET http://{{host_ezstrean}}:{{port_ezstream}}/health_check