### Health Check

GET http://{{ezstream_host}}:{{ezstream_port}}/health_check


### SetUp ezstream (create)

POST http://{{ezstream_host}}:{{ezstream_port}}/{{mount_main}}/create

###

POST http://{{ezstream_host}}:{{ezstream_port}}/{{mount_jazz}}/create

### SetUp ezstream (update)

POST http://{{ezstream_host}}:{{ezstream_port}}/{{mount_jazz}}/update

[
  "/source/2006 - Сквозное (EP)/01. Хочешь.mp3",
  "/source/2006 - Сквозное (EP)/02. Приоритеты.mp3",
  "/source/2006 - Сквозное (EP)/03. Простые слова.mp3"
]

###

POST http://{{ezstream_host}}:{{ezstream_port}}/{{mount_main}}/update

[
  "/source/1996 - Panorama 94-96/01 Mnemosyne.mp3",
  "/source/1996 - Panorama 94-96/02 The Sky Horses.mp3",
  "/source/1996 - Panorama 94-96/03 Spuma.mp3",
  "/source/1996 - Panorama 94-96/04 Eldolon.mp3",
  "/source/1996 - Panorama 94-96/05 Aither.mp3",
  "/source/1996 - Panorama 94-96/06 L'Architecture Secrete.mp3",
  "/source/1996 - Panorama 94-96/07 Panorama.mp3",
  "/source/1996 - Panorama 94-96/08 L'Appel Du Froid.mp3",
  "/source/1996 - Panorama 94-96/09 Carmina.mp3",
  "/source/1996 - Panorama 94-96/10 Arimathie's Rain.mp3"
]


### Next

GET http://{{ezstream_host}}:{{ezstream_port}}/{{mount_main}}/next

###


GET http://{{ezstream_host}}:{{ezstream_port}}/{{mount_jazz}}/next