### Health Check

GET http://{{host}}:{{port}}/health_check

### Update database from meta.json

GET http://{{host}}:{{port}}/internal/update_db


###

GET http://{{host}}:{{port}}/internal/{{mount}}/track
###

GET http://{{host}}:{{port}}/internal/{{mount}}/next

###

GET http://{{host}}:{{port_internal}}/check



###

GET http://{{host}}:{{port_internal}}/internal/create_and_run

###

POST http://{{host}}:{{port_internal}}/internal/main/update
Content-Type: application/json

[
  "/source/2006 - Сквозное (EP)/01. Хочешь.mp3",
  "/source/2006 - Сквозное (EP)/02. Приоритеты.mp3",
  "/source/2006 - Сквозное (EP)/03. Простые слова.mp3"
]


###

POST http://{{host}}:{{port_internal}}/internal/jazz/update
Content-Type: application/json

[
  "/source/1996 - Panorama 94-96/01 Mnemosyne.mp3",
  "/source/1996 - Panorama 94-96/02 The Sky Horses.mp3",
  "/source/1996 - Panorama 94-96/03 Spuma.mp3",
  "/source/1996 - Panorama 94-96/04 Eldolon.mp3",
  "/source/1996 - Panorama 94-96/05 Aither.mp3",
  "/source/1996 - Panorama 94-96/06 L'Architecture Secrete.mp3",
  "/source/1996 - Panorama 94-96/07 Panorama.mp3",
  "/source/1996 - Panorama 94-96/08 L'Appel Du Froid.mp3",
  "/source/1996 - Panorama 94-96/09 Carmina.mp3",
  "/source/1996 - Panorama 94-96/10 Arimathie's Rain.mp3"
]