version: "3"

services:
  yandex-disk:
    build: ./disk
    container_name: yandex-disk
    volumes:
      - /root/Yandex.Disk:/root/Yandex.Disk
    restart: always
    privileged: true
  postgres:
    image: postgres
    container_name: postgres
#    [debug]
#    ports:
#      - "1337:5432"
    env_file: .env
  api:
    build:
      context: ./radio_console
    env_file: .env
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ezstream
      - icecast
    volumes:
      - ./source:/source
      - /root/Yandex.Disk:/root/Yandex.Disk
  ezstream:
    build:
      context: ./ezstream
    container_name: ezstream
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
       - ./source:/source
       - /root/Yandex.Disk:/root/Yandex.Disk
    depends_on:
      - icecast
  icecast:
    build:
      context: ./icecast
    container_name: icecast
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
      - "8006:8006"
    volumes:
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml
      - ./icecast/logs:/var/log/icecast2 WTF?
