###

GET http://{{host}}:{{port}}/health_check

###

GET http://{{host}}:{{port}}/internal/update_db


###

GET http://{{host}}:{{port}}/internal/{{mount}}/track
###

GET http://{{host}}:{{port}}/internal/{{mount}}/next

###

GET http://{{host}}:{{port_internal}}/check